### ISSUE TITLE
Add conformance section

### ISSUE THREAD

**Issue by dhvenema** [Geonovum/respec#35]
Adjust and add the conformance section to geonovum-respec. This is related to conformance.js, informative.js and conformance.html.
* conformance should be "conformiteit"
* non-normative should be "informatief"
* normative should be "normatief"

@lvdbrink Translation for:
* This section is non-normative.
* As well as sections marked as non-normative, all authoring guidelines, diagrams, examples, and notes in this specification are non-normative. Everything else in this specification is normative.

**Comment by lvdbrink** [comment]
"- Dit onderdeel is niet normatief."
"- Naast onderdelen die als niet normatief gemarkeerd zijn, zijn ook alle diagrammen, voorbeelden, en noten in dit document niet normatief. Verder is alles in dit document normatief."

NB "authoring guidelines" would be translated as "auteursaanwijzingen". However, I omitted this because I don't think we ever have these in our documents.
